name: update
on: 
  push:
  schedule:
    - cron: '0 2 * * 0'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      - name: execute sh script 
        run: |
         chmod 777 ./bin/mirror_worldvectorlogo_download.sh
         ./bin/mirror_worldvectorlogo_download.sh
        env:
          key: ${{ secrets.key }} 
      - name: Commit files 
        run: |
         git config --local user.name "SVGBOT"
         git add .
         git commit -m "Downloading SVGs"
      - name: Push changes # push the output folder to your repo
        uses: ad-m/github-push-action@master
        with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         force: true